import { useEffect, useState } from 'react';
import { Layout, useHeroSlider } from './BigweinCommon';
import SearchPanel from './SearchPanel';
import { CategoryCard, PropertyCard, ProjectCard } from './Cards';
import { fallbackCategories, fallbackProperties, fallbackProjects, loadCategories, loadHomeData, loadProjects, img } from './apiData';
import Link from "next/link";


export default function HomePage() {
  const slide = useHeroSlider();
  const [data, setData] = useState({ properties: fallbackProperties, categories: fallbackCategories, projects: fallbackProjects });
  useEffect(() => { (async () => { const [home, cats, projects] = await Promise.all([loadHomeData(), loadCategories(), loadProjects()]); setData({ properties: home.properties.length ? home.properties : fallbackProperties, categories: cats.length ? cats : fallbackCategories, projects: projects.length ? projects : fallbackProjects }); })() }, []);
  const slides = [img('detail-hero-building.jpg'), img('villa.jpg'), img('house.jpg'), img('apartment.jpg')];
  return <Layout className="bigwein-theme home-page"><main><section className="lux-hero reduced-hero"><div className="lux-container lux-hero-grid"><div className="lux-hero-copy"><span className="lux-kicker">Premium Real Estate Marketplace</span><h1>Find Your Dream Home</h1><p>Explore curated properties tailored to your lifestyle, investment goals and dream home vision.</p></div><div className="lux-hero-art lux-hero-slider">{slides.map((s, i) => <div key={s} className={`lux-slide ${slide === i ? 'active' : ''}`}><img alt="Featured property" src={s} /></div>)}<div className="lux-slider-nav">{slides.map((_, i) => <span key={i} className={slide === i ? 'active' : ''}></span>)}</div></div></div><div className="lux-container"><SearchPanel /></div></section>
    <section className="bw-categories lux-section"><div className="lux-container"><div className="bw-section-head"><div><h2>Find by category</h2><p>Choose the right property type based on your lifestyle and investment goals.</p></div><Link className="bw-link-btn" href="/properties">View All</Link></div><div className="bw-category-grid">{data.categories.slice(0, 6).map(c => <CategoryCard key={c.id || c.category} category={c} />)}</div></div></section>
    <section className="bw-featured lux-section"><div className="lux-container"><div className="bw-section-head"><div><h2>Featured properties</h2><p>Curated premium listings with strong location value and better buyer interest.</p></div><Link className="bw-red-btn" href="/properties">Explore Properties</Link></div><div className="bw-property-grid">{data.properties.slice(0, 3).map(p => <PropertyCard key={p.id} property={p} />)}</div></div></section>
    <section className="bw-projects lux-section"><div className="lux-container"><div className="bw-section-head"><div><h2>Premium projects</h2><p>Discover under-construction and ready-to-move projects from trusted developers.</p></div><Link className="bw-red-btn" href="/projects">View Projects</Link></div><div className="bw-property-grid">{data.projects.slice(0, 3).map((p, i) => <ProjectCard key={p.id || i} project={p} />)}</div></div></section>
    <section className="bw-faq lux-section" id="faq"><div className="lux-container bw-faq-grid"><div className="bw-faq-copy"><h2>Frequently asked questions</h2><p>Answers for buyers, sellers, owners and agents using the Bigwein real estate platform.</p><Link className="bw-red-btn" href="/login">Post Property</Link></div><div className="bw-accordion"><article className="faq-item open"><button className="faq-q" type="button">How do I search for properties? <i className="fa-solid fa-plus"></i></button><div className="faq-a">Use search, property type, budget, BHK and Smart Filter options to shortlist matching properties.</div></article><article className="faq-item"><button className="faq-q" type="button">Can owners post properties? <i className="fa-solid fa-plus"></i></button><div className="faq-a">Yes. Owners, agents and builders can post properties after registering.</div></article></div></div></section>
  </main></Layout>;
}
