import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/router';
import { Layout } from './BigweinCommon';
import { PropertyCard } from './Cards';
import { fallbackImages, fallbackProperties, loadProperties, loadProperty, paramValue, price } from './apiData';

function galleryImages(property){
  const raw = property?.gallery || [];
  const imgs = raw.map(x => typeof x === 'string' ? x : (x.image || x.name || x.url)).filter(Boolean);
  return imgs.length ? imgs : fallbackImages;
}
export default function PropertyDetailPage({ slug }){
  const router = useRouter();
  const finalSlug = slug || router.query.slug || 'modern-haven-villai';
  const [property,setProperty]=useState(fallbackProperties[0]);
  const [similar,setSimilar]=useState(fallbackProperties);
  const [active,setActive]=useState(0);
  useEffect(()=>{(async()=>{const p=await loadProperty(finalSlug); if(p) setProperty(p); const list=await loadProperties({limit:4}); setSimilar(list.length?list:fallbackProperties);})()},[finalSlug]);
  const imgs=useMemo(()=>galleryImages(property),[property]);
  return <Layout className="bigwein-theme exact-detail-page"><main>
    <section className="eb-detail-hero full-width-detail"><div className="container"><div className="eb-hero-image"><img alt={property.title} src={imgs[active] || property.title_image}/><button className="arrow left" onClick={()=>setActive((active+imgs.length-1)%imgs.length)}><i className="fa-solid fa-chevron-left"></i></button><button className="arrow right" onClick={()=>setActive((active+1)%imgs.length)}><i className="fa-solid fa-chevron-right"></i></button></div><div className="eb-thumb-strip">{imgs.slice(0,5).map((im,i)=><img key={im+i} alt="Property" onClick={()=>setActive(i)} className={active===i?'active':''} src={im}/>)}</div><div className="eb-title-card"><div><div className="chips"><span><i className="fa-solid fa-building"></i> {property.category?.category || 'Property'}</span><span><i className="fa-regular fa-clock"></i> Recently Updated</span></div><h1>{property.title}</h1><p><i className="fa-solid fa-location-dot"></i> {[property.city, property.state, property.country].filter(Boolean).join(', ') || 'Bhuj, Gujarat, India'}</p></div><div className="eb-price"><small>Property For</small><span>{property.property_type === 'rent' ? 'Rent' : 'Sell'}</span><strong>{price(property.price)}</strong><div className="icon-meta"><span><i className="fa-solid fa-bed"></i> {paramValue(property,['bed'],'5')}</span><span><i className="fa-solid fa-bath"></i> {paramValue(property,['bath'],'4')}</span><span><i className="fa-solid fa-door-open"></i> {paramValue(property,['room'],'2')}</span><span><i className="fa-solid fa-ruler-combined"></i> {paramValue(property,['area','sqft'],'1500')}</span></div></div></div></div></section>
    <section className="eb-body-section"><div className="container eb-detail-grid"><div className="eb-left"><div className="eb-box"><h2>About Property</h2><p>{property.description || 'A stunning modern villa, showcasing the beauty of premium living with warm spaces, privacy, natural light and a comfortable family lifestyle.'}</p></div><div className="eb-box amenities-card"><h2>Feature & Amenities</h2><div className="eb-features feature-ref-grid"><div><i className="fa-solid fa-bed"></i><span>Bedroom</span><b>{paramValue(property,['bed'],'4')}</b></div><div><i className="fa-solid fa-bath"></i><span>Bathroom</span><b>{paramValue(property,['bath'],'4')}</b></div><div><i className="fa-solid fa-building-columns"></i><span>Balconies</span><b>{paramValue(property,['balcon'],'2')}</b></div><div><i className="fa-solid fa-ruler-combined"></i><span>Build Area</span><b>{paramValue(property,['build','area'],'1500')}</b></div><div><i className="fa-solid fa-vector-square"></i><span>Carpet Area</span><b>{paramValue(property,['carpet'],'1800')}</b></div><div><i className="fa-solid fa-couch"></i><span>Furnishing</span><b>{paramValue(property,['furnish'],'Furnished')}</b></div><div><i className="fa-solid fa-house-circle-check"></i><span>Status</span><b>{paramValue(property,['status'],'Ready to Move')}</b></div><div><i className="fa-solid fa-user-tie"></i><span>Listed by</span><b>{property.raw?.added_by || 'Owner'}</b></div></div></div><div className="eb-box"><h2>Outdoor Facilities</h2><div className="eb-outdoor"><span><i className="fa-solid fa-hospital"></i> Hospital <b>1 km</b></span><span><i className="fa-solid fa-store"></i> Supermarket <b>1 km</b></span><span><i className="fa-solid fa-dumbbell"></i> Gym <b>2 km</b></span><span><i className="fa-solid fa-bus"></i> Bus Station <b>1 km</b></span></div></div><div className="eb-box"><h2>Property Address</h2><div className="eb-address"><p><b>Address</b><br/>{property.address || 'GJ6'}</p><p><b>City</b><br/>{property.city || 'Bhuj'}</p><p><b>Country</b><br/>{property.country || 'India'}</p><p><b>State</b><br/>{property.state || 'Gujarat'}</p></div><div className="eb-map clear-map"><button>View Map</button></div></div></div><aside className="eb-sidebar"><div className="owner-card"><div className="owner-head"><img alt="Advisor" src="/bigwein/assets/images/houseinhand.jpg"/><div><h3>Bigwein Advisor</h3><p>Property Consultant</p></div></div><div className="owner-detail"><i className="fa-solid fa-location-dot"></i><span>Address<br/><b>{property.city || 'Bhuj'}, {property.state || 'Gujarat'}</b></span></div><div className="owner-detail"><i className="fa-solid fa-phone"></i><span>Contact<br/><b>+91 96001 45254</b></span></div><button className="btn btn-primary full-btn"><i className="fa-solid fa-phone"></i> Contact</button></div></aside></div></section>
    <section className="eb-compare-wide-section"><div className="container"><h2>Compare With Similar Properties</h2><div className="eb-compare-wide-grid four-card-grid">{similar.slice(0,4).map(p=><PropertyCard key={p.id} property={p}/>)}</div></div></section>
  </main></Layout> }
